### ISSUE TITLE
GStreamer Error when running from virtualbox

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Onboard-Media-Control#7]
The program currently throws the following warnings:
`Warning: "No decoder available for type 'audio/mpeg, mpegversion=(int)1, mpegaudioversion=(int)1, layer=(int)3, rate=(int)44100, channels=(int)2, parsed=(boolean)true'."
Error: "Your GStreamer installation is missing a plug-in."`

When running from a virtualbox (Tested on both Bill's and Ben's machines).

**Comment by ExtraGravity** [comment]
The issue is not from virtualbox. The issue is the distribution of linux. Xenial's default apt-get PPA does not have the proper gstreamer0.10 plugins because gstreamer0.10 is being deprecated for gstreamer1.0  even though QT still uses gstreamer0.10. You can manually find the deprecated plugins online and install the .deb files for xenial there.
